// controlador/config.js
window.SUPABASE_URL = 'https://kwwwlauizjnjwhsaztfp.supabase.co';
window.SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt3d3dsYXVpempuandoc2F6dGZwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQzNDY0MTksImV4cCI6MjA3OTkyMjQxOX0.qzHqdnLuZdxsrWAcc7BY8xSDOenRTccLG4c5QNTXSNM';